"""spare

Revision ID: b32011229ace
Revises: be1387af84d0
Create Date: 2025-11-26 13:59:25.170759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32011229ace'
down_revision: Union[str, Sequence[str], None] = 'be1387af84d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_category'), 'spare_parts', ['category'], unique=False)
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_name'), 'spare_parts', ['name'], unique=False)
    op.create_index(op.f('ix_spare_parts_sku'), 'spare_parts', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_parts_sku'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_name'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_category'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
